
export const currencyConstants = {
    SET_CURRENCIES: "SET_CURRENCIES",
    SET_API_ERROR: "SET_API_ERROR",
    SET_CURRENCY_ONE: "SET_CURRENCY_ONE",
    SET_CURRENCY_TWO: "SET_CURRENCY_TWO",
    SET_CURRENCY_VALUE: "SET_CURRENCY_VALUE",
    SET_TOTAL_VALUE: "SET_TOTAL_VALUE",
    SET_TOTAL_TO_CONVERT: "SET_TOTAL_TO_CONVERT",
    SET_COUNTRIES_LIST: "SET_COUNTRIES_LIST"
}